Implement new gateway
dc-Ragnarok/Fenrir pull request #38
Opened 2023-05-08 18:53 UTC by Exanlv

2023-05-09 20:16 UTC, Exanlv commented
resolves #35 
resolves #34

2023-05-10 12:03 UTC, CommandString requested changes

2023-05-10 12:25 UTC, Exanlv commented on src/Gateway/Handlers/HeartbeatAcknowledgedEvent.php
> +        return '11';
~how did I not come up with this myself~

2023-05-10 17:32 UTC, CommandString approved these changes

2023-05-10 17:33 UTC, merged